#!/usr/bin/env python3
"""Fetch public.bib from every repo in the ftsrg-papers org that has one,
and concatenate them into publications.bib for the BibBase-powered index site.

Requires GH_TOKEN with Contents:read + Metadata:read on all org repos.
Falls back to public repos only when GITHUB_TOKEN is used.
"""

import base64
import json
import os
import re
import urllib.error
import urllib.request

ORG   = "ftsrg-papers"
SELF  = f"{ORG}.github.io"
TOKEN = os.environ.get("GH_TOKEN", "")
OUT   = "publications.bib"


def _get(url: str):
    """GET *url* via the GitHub API; return parsed JSON or None on 404."""
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github.v3+json")
    req.add_header("User-Agent", f"{ORG}-index-workflow")
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return None
        raise


def get_all_repos() -> list:
    repos, page = [], 1
    while True:
        batch = _get(
            f"https://api.github.com/orgs/{ORG}/repos"
            f"?per_page=100&page={page}&sort=full_name"
        )
        if not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return repos


def get_bib(repo_name: str) -> str | None:
    """Return the raw content of public.bib for *repo_name*, or None."""
    meta = _get(
        f"https://api.github.com/repos/{ORG}/{repo_name}/contents/public.bib"
    )
    if not meta or "content" not in meta:
        return None
    return base64.b64decode(meta["content"]).decode("utf-8")


# Matches a complete BibTeX entry (@type{ ... }), assuming the closing
# brace sits alone at the start of a line (standard formatting).
_ENTRY_RE = re.compile(r"@\w+\{.*?^\}", re.MULTILINE | re.DOTALL)


def rewrite_bib(content: str, repo_name: str) -> str:
    """Patch every BibTeX entry in *content* for use in the org index:

    1. Replace  ./path  with  /repo-name/path  in all url-type fields.
    2. Set  url = {/repo-name/}  so BibBase links the title to the
       repo’s gh-pages site (adds the field if absent, overrides if present).
    """
    base = f"/{repo_name}/"

    # 1. Rewrite relative paths in any url / url_* field
    content = re.sub(
        r"(url\w*\s*=\s*\{)\./",
        lambda m: m.group(1) + base,
        content,
    )

    # 2. Per-entry: set/override the plain `url` field
    def _patch(m: re.Match) -> str:
        entry = m.group(0)
        replacement = f"url = {{{base}}}"
        if re.search(r"\burl\s*=", entry):
            # Override the existing value (url values never contain braces)
            return re.sub(r"\burl\s*=\s*\{[^}]*\}", replacement, entry)
        # Inject before the closing } of the entry
        return re.sub(r"(^\})", f"  {replacement},\n\\1", entry, flags=re.MULTILINE)

    return _ENTRY_RE.sub(_patch, content)


def main() -> None:
    print(f"Fetching repos for org '{ORG}'…")
    all_repos = get_all_repos()
    print(f"  {len(all_repos)} repos found.")

    chunks: list[str] = []
    for repo in all_repos:
        name: str = repo["name"]
        if name == SELF:
            continue

        print(f"  {name}: ", end="", flush=True)
        bib = get_bib(name)
        if bib is None:
            print("no public.bib — skipped.")
            continue

        print("included.")
        rule = "─" * max(0, 50 - len(name))
        chunks.append(f"% ── {name} {rule}\n{rewrite_bib(bib.strip(), name)}\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(
            "% Auto-generated by the update-repos workflow.\n"
            "% Do not edit manually — changes will be overwritten.\n\n"
        )
        fh.write("\n".join(chunks))
        if chunks:
            fh.write("\n")

    print(f"\nWrote {len(chunks)} repositories to {OUT}.")


if __name__ == "__main__":
    main()
